In [106]:
import numpy as np

Valid Sudoku

In [107]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [108]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [109]:
b= np.sum(s,axis=1)

In [110]:
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [111]:
b==45 # for check

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [112]:
# check using for loop (Rows)

In [113]:
for i in b:
    if i!=45:
        print("Sudoku in not vaild")
        break
else:
    print("For Row Sudoku is vaild")
        

For Row Sudoku is vaild


In [114]:
#Columns

In [115]:
c= np.sum(s,axis=0)

In [116]:
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [117]:
c==45 #for Check

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [118]:
# check using for loop (Columns)

In [119]:
for i in c:
    if i!=45:
        print("Sudoku in not vaild")
        break
else:
    print("For Columns Sudoku is vaild")
    
        

For Columns Sudoku is vaild


In [120]:
# FOR EVERY SINGLE BLOCK

In [121]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [122]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [123]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n =s[i:i+3,j:j+3]
        print(n.sum())
    

45
45
45
45
45
45
45
45
45


General Questions

In [124]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [125]:
#Get the shape of the matrix.

In [126]:
data.shape

(5, 3)

In [127]:
#Find the average age of students.

In [128]:
np.mean(data[:,0])

np.float64(18.4)

In [129]:
#Extract Math marks of all students.

In [130]:
data[:,1]

array([85, 92, 76, 65, 90])

In [131]:
#Find the highest Science mark.

In [132]:
np.max(data[:,2])

np.int64(95)

In [133]:
#Get details of the student who scored more than 90 in Math.

In [134]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [135]:
#Increase Math marks of all students by 5.

In [136]:
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [137]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [138]:
#Find how many students are younger than 19.

In [139]:
len(data[data[:,0]<19])

3

In [140]:
#Calculate the average marks in each subject (column-wise mean).

In [141]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [142]:
#Get data of students who scored at least 80 in both subjects.

In [143]:
data[(data[:,1] >=80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [144]:

#Replace all Science marks < 75 with 0.

In [145]:
data[:,2][data[:,2]<75]=0

In [146]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])